pipeline {
    agent any
    stages {
        stage('Restore') {
            steps {
                dir('src') {
                    sh 'dotnet restore Abstraccion.csproj'
                }
            }
        }
        stage('Build') {
            steps {
                dir('src') {
                    sh 'dotnet build Abstraccion.csproj --no-restore'
                }
            }
        }
        stage('Test') {
            steps {
                dir('tests') {
                    sh 'dotnet test AbstraccionTests.csproj --no-restore --no-build'
                }
            }
        }
    }
}
