pipeline {
    agent any

    stages {
        stage('Clonar') {
            steps {
                checkout scm
            }
        }

        stage('Construcción') {
            steps {
                dir('temas/anotaciones/cpp') {
                    script {
                        sh 'docker build -t anotaciones-cpp .'
                    }
                }
            }
        }

        stage('Pruebas') {
            steps {
                script {
                    // Asumimos que el Makefile tiene una regla `test` o similar.
                    // Si no, ejecuta directamente los binarios de prueba.
                    sh 'docker run --rm anotaciones-cpp make test'
                }
            }
        }

        stage('Ejecución') {
            steps {
                script {
                    sh 'docker run --rm anotaciones-cpp ./main'
                }
            }
        }
    }

    post {
        always {
            echo '--- Pipeline finalizado. Limpiando contenedores colgados (si los hubiera) ---'
            sh 'docker ps -aq --filter status=exited | xargs --no-run-if-empty docker rm'
        }
    }
}
