pipeline {
    agent {
        docker {
            image 'maven:3.8.6-eclipse-temurin-17'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    environment {
        MAVEN_OPTS = "-Dmaven.repo.local=/root/.m2/repository"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir('temas/inyeccion/java-02/inyeccion') {
                    script {
                        sh 'docker build -t inyeccion-java .'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('temas/inyeccion/java-02/inyeccion') {
                    script {
                        sh 'docker run --rm inyeccion-java mvn test'
                    }
                }
            }
        }

        stage('Run Application') {
            steps {
                dir('temas/inyeccion/java-02/inyeccion') {
                    script {
                        sh 'docker run --rm inyeccion-java'
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completado.'
        }
    }
}
