pipeline {
    agent any

    stages {
        stage('Construcción') {
            steps {
                sh 'docker build -t inyeccion-java .'
            }
        }
        stage('Pruebas') {
            steps {
                sh 'docker run --rm inyeccion-java mvn test'
            }
        }
        stage('Ejecución') {
            steps {
                sh 'docker run --rm inyeccion-java'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completado.'
        }
    }
}
