# Rakefile

require "rake/testtask"

Rake::TestTask.new do |t|
  t.pattern = "test/test_*.rb"  # Ejecuta todos los archivos de test
  t.warning = true              # Muestra advertencias
end

task default: :test