pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                dir('temas/lambdas/python-04/src') {
                    sh 'python3 -m py_compile Program.py'
                }
            }
        }
        stage('Test') {
            steps {
                dir('temas/lambdas/python-04/tests') {
                    sh 'python3 -m unittest LambdaTests.py'
                }
            }
        }
    }
}
