pipeline {
    agent {
        docker {
            image 'scala-herencia:dev'
            args '-v $PWD:/app -w /app'
        }
    }

    stages {
        stage('Compilar') {
            steps {
                sh 'sbt compile'
            }
        }

        stage('Test') {
            steps {
                sh 'sbt test'
                sh 'ls -l target/test-reports || echo "No se encontró el directorio"'
            }
        }
        
        stage('Empaquetar') {
            steps {
                sh 'sbt package'
                sh 'ls -l target/scala-2.13/' 
            }
        }
    }

    post {
        always {
            junit 'target/test-reports/*.xml'
        }
    }
}

