pipeline {
    agent any

    environment {
        SBT_IMAGE = 'scala-herencia:dev'
    }

    stages {
        stage('Compilar y testear') {
            steps {
                script {
                    docker.image(env.SBT_IMAGE).inside('-v $PWD:/app -w /app') {
                        sh 'sbt compile'
                        sh 'sbt test'
                    }
                }
            }
        }
    }

    post {
        always {
            junit 'target/test-reports/*.xml'
        }
    }
}

