pipeline {
    agent {
        docker {
            image 'gradle:jdk17'  // imagen oficial con Gradle y JDK 17
            args '-v $HOME/.gradle:/home/gradle/.gradle'  // para cachear dependencias
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                sh 'chmod +x ./temas/errores/kotlin/gradlew'  // si usas gradlew local
                sh './temas/errores/kotlin/gradlew clean test' // ejecuta build y pruebas
            }
        }
    }

    post {
        always {
            junit 'temas/errores/kotlin/build/test-results/test/*.xml'  // recoge reportes JUnit
        }
    }
}
