pipeline {
  agent any

  environment {
    DART_HOME = "/usr/lib/dart/bin"
    PATH = "${env.PATH}:${env.DART_HOME}"
  }

  stages {
    stage('Instalar dependencias') {
      steps {
        dir('temas/herencia/dart') {
          sh 'dart pub get'
        }
      }
    }

    stage('Analizar código') {
      steps {
        dir('temas/herencia/dart') {
          sh 'dart analyze lib/'
        }
      }
    }

    stage('Ejecutar tests') {
      steps {
        dir('temas/herencia/dart') {
          sh 'dart test test/test.dart'
        }
      }
    }

    stage('Empaquetar') {
      steps {
        dir('temas/herencia/dart') {
          sh 'tar -czvf personaje_package.tar.gz lib/ test/ pubspec.yaml'
          archiveArtifacts artifacts: 'personaje_package.tar.gz', fingerprint: true
        }
      }
    }
  }

  post {
    always {
      echo "Pipeline finalizado."
    }
    success {
      echo "Éxito total: Build, test y empaquetado."
    }
    failure {
      echo "Algo falló."
    }
  }
}
