pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Test') {
            steps {
                dir('temas/aspectos/java-03/mi-proyecto') {
                    sh 'mvn clean test'
                }
            }
            post {
                always {
                    junit 'temas/aspectos/java-03/mi-proyecto/target/surefire-reports/*.xml'
                }
            }
        }
    }
}
