pipeline {
    agent any

    stages {
        stage('Preparar entorno') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install --upgrade pip'
            }
        }

        stage('Ejecutar pruebas') {
            steps {
                sh './venv/bin/python -m unittest test_trabajadores.py'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
        }
    }
}
