pipeline {
    agent {
        docker { image 'maven:3.9.4-eclipse-temurin-17' }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build & Test') {
            steps {
                sh 'mvn clean verify'
            }
        }
        stage('Run') {
            steps {
                // Ejecutar la app para validar si quieres, o eliminar esta etapa
                sh 'mvn exec:java -Dexec.mainClass=com.example.App'
            }
        }
    }
    post {
        always {
            junit '**/target/surefire-reports/*.xml' // Reporte de tests
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }
    }
}
