pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t anotaciones:latest .'
            }
        }

        // stage('Push Docker Image') {
        //     steps {
        //         withDockerRegistry([credentialsId: 'docker-hub', url: '']) {
        //             sh 'docker push anotaciones:latest'
        //         }
        //     }
        // }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}
