pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-17'
        }
    }
    stages {
        stage('Build') {
            steps {
                dir('temas/inyeccion/java/inyeccion') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('temas/inyeccion/java/inyeccion') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'temas/inyeccion/java/inyeccion/target/surefire-reports/*.xml'
                }
            }
        }
    }
}
