pipeline {
    agent any

    stages {
        stage('Compilar') {
            steps {
                dir('temas/inyeccion/java-01') {
                    echo 'Compilando el proyecto...'
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test de MainTest.java') {
            steps {
                dir('temas/inyeccion/java-01') {
                    echo 'Ejecutando programa principal...'
                    sh 'mvn test'
                }
            }
        }
    }

    post {
        success {
            echo 'Compilación y ejecución completadas con éxito.'
        }
        failure {
            echo 'Hubo un error en el pipeline.'
        }
    }
}
