pipeline {
    agent any

    stages {
        stage('Construcción') {
            steps {
                sh 'docker build -t inyeccion-cpp .'
            }
        }
        stage('Pruebas') {
            steps {
                sh 'docker run --rm inyeccion-cpp ctest --test-dir build'
            }
        }
        stage('Ejecución') {
            steps {
                sh 'docker run --rm inyeccion-cpp ./build/main'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completado.'
        }
    }
}
