pipeline {
    agent any

    stages {
        stage('Construcción y Pruebas') {
            steps {
                sh 'docker build -t inyeccion-cpp .'
                sh 'docker run --rm inyeccion-cpp'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completado.'
        }
    }
}
