pipeline {
    agent {
        docker {
            image 'node:18'
        }
    }

    stages {
        stage('Node Version') {
            steps {
                sh 'node --version'
            }
        }

        stage('Instalar dependencias') {
            steps {
                dir('temas/errores/javascript-01') {
                    sh 'npm i'
                }
            }
        }

        stage('Ejecutar tests') {
            steps {
                dir('temas/errores/javascript-01') {
                    sh 'npm test'
                }
            }
        }
    }

    post {
        always {
            script {
                echo 'Terminado'
            }
        }
    }
}
