pipeline {
    agent {
        docker {
            image 'node:18'
        }
    }

    stages {
        stage('Instalar dependencias') {
            steps {
             
                    sh 'npm install'
                
            }
        }

        stage('Ejecutar tests') {
            steps {
                 
                    sh 'npm test'
                
            }
        }
    }
}
