pipeline {
    agent any

    stages {
        stage('Preparar entorno') {
            steps {
                echo 'Preparando entorno Typescript...'
                sh 'node -v'
                sh 'npm -v'
            }
        }

        stage('Instalar dependencias') {
            steps {
                echo 'Instalando dependencias...'
                dir('temas/anotaciones/typescript') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Construyendo...'
                dir('temas/anotaciones/typescript') {
                    sh 'npm run build'
                }
            }
        }

        stage('Ejecutar pruebas') {
            steps {
                echo 'Ejecutando pruebas con Jest...'
                dir('temas/anotaciones/typescript') {
                    sh 'npm test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
        }
        failure {
            echo 'La ejecución falló.'
        }
        success {
            echo 'La ejecución fue exitosa.'
        }
    }
}