pipeline {
    agent any

    environment {
        SCALA_VERSION = '2.13.12'
    }

    stages {
        stage('Clean') {
            steps {
                dir('temas/herencia/Scala-01') {
                    sh 'sbt clean'
                }
            }
        }
        stage('Build') {
            steps {
                dir('temas/herencia/Scala-01') {
                    sh 'sbt compile'
                }
            }
        }
        stage('Test') {
            steps {
                dir('temas/herencia/Scala-01') {
                    sh 'sbt test'
                }
            }
        }
    }
}
