#Utilizamos la imagen oficial de Jenkins como base 
FROM jenkins/jenkins:lts

#Cambiamos al usuario root para poder instalas software dentro del contenedor ya que el usuario jenkins por defecto no puede
USER root

# Instalar Docker CLI en Jenkins
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli

USER jenkins

# Plugins para usar Docker y BlueOcean
RUN jenkins-plugin-cli --plugins "docker-workflow blueocean"
