pipeline {
    agent any

    stages {
        stage('Clonar') {
            steps {
                checkout scm
            }
        }

        stage('Construcción') {
            steps {
                dir('temas/abstraccion/typescript') {
                    script {
                        sh 'docker build -t abstraccion-typescript .'
                    }
                }
            }
        }

        stage('Pruebas') {
            steps {
                script {
                    sh 'docker run --rm abstraccion-typescript npm run test'
                }
            }
        }

        stage('Ejecución') {
            steps {
                script {
                    sh 'docker run --rm abstraccion-typescript npm run start'
                }
            }
        }
    }

    post {
        always {
            echo '--- Pipeline finalizado. Limpiando contenedores colgados (si los hubiera) ---'
            sh 'docker ps -aq --filter status=exited | xargs --no-run-if-empty docker rm'
        }
    }
}
