pipeline {
    agent {
        dockerfile {
            filename 'despliegue/Dockerfile'
            dir '.'
            additionalBuildArgs '--build-arg DEBIAN_FRONTEND=noninteractive'
        }
    }
    stages {
        stage('Compile') {
            steps {
                sh 'sbt compile'
            }
        }
        stage('Test') {
            steps {
                sh 'sbt test'
            }
        }
    }
}
