pipeline {
    agent {
        docker{
            image 'python:3.9-slim'
        }

    }
        
    stages {
        stage('Preparar entorno') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install --upgrade pip'
            }
        }

        stage('Ejecutar pruebas') {
            steps {
                sh './venv/bin/python temas/herencia/python/test.py'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
        }
    }
}
