pipeline {
    agent any

    stages {
        stage('Clonar') {
            steps {
                checkout scm
            }
        }

        stage('Construir imagen Docker') {
            steps {
                script {
                    sh 'docker build -t herencia-python .'
                }
            }
        }

        stage('Ejecutar tests') {
            steps {
                script {
                    sh 'docker run --rm herencia-python'
                }
            }
        }
    }
}
