pipeline {
    agent {
        docker {
            image "csharp"
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        DOTNET_CLI_TELEMETRY_OPTOUT = 1
        PROJECT_DIR = 'temas/abstraccion/src/c#'
        TEST_DIR = 'temas/abstraccion/src/test'
    }

    stages {
        stage ('Clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Compilar') {
            steps {
                dir(env.PROJECT_DIR) {
                    sh 'dotnet build'
                }
            }
        }

        stage('Test') {
            steps {
                dir(env.TEST_DIR) {
                    sh 'dotnet test --logger "trx;LogFileName=../TestResults/results.trx"'
                }
            }
        }

        stage('Empaquetar') {
            steps {
                dir(env.PROJECT_DIR) {
                    sh 'dotnet publish -c Release -o ./publish'
                    archiveArtifacts artifacts: 'publish/**/*', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            junit '**/TestResults/*.trx'
            echo "Pipeline completado - Resultado: ${currentBuild.currentResult}"
        }
        failure {
            echo '¡Pipeline fallido! Revisa los logs.'
            archiveArtifacts artifacts: '**/*.log', fingerprint: true
        }
    }
}